{
 "title": "Idun PSO RED Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SOURCE", "label": "Environment", "query": "prometheus" },
   { "name": "Service", "label": "Service", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Rate per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$Service\"}[15m])) by (uri,method)",
     "legendFormat": "{{method}} --> {{uri}}"
    }
   ]
  },
  {
   "title": "Average Response Latency per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{app=\"$Service\", status!~\"500\"}[15m]))/sum(rate(http_server_requests_seconds_count{app=\"$Service\", status!~\"500\"}[15m]))",
     "legendFormat": "HTTP-AVG"
    },
    {
     "expr": "topk(5, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"$Service\"}[15m])))",
     "legendFormat": "HTTP-MAX --> {{uri}}"
    }
   ]
  },
  {
   "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[15m])) by (le))",
     "legendFormat": "100%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[15m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[15m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[15m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[15m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[15m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Error Rate per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$Service\", status!~\"2..\"}[1h]))by (uri,method)",
     "legendFormat": "{{method}} --> {{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 API's by Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"$Service\"}[15m])))",
     "legendFormat": "{{method}} --> {{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs by Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"$Service\"}[15m])))",
     "legendFormat": "{{method}} --> {{uri}}"
    }
   ]
  }
 ]
}