{
 "title": "Idun - Overall Resource View",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Environment", "query": "prometheus" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Idun Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Idun CPU Usage - Hourly",
   "type": "stat",
   "description": "Metric used: container_memory_usage_bytes, kube_pod_container_resource_requests, kube_pod_container_resource_limits_memory_bytes\n\nThis graph shows the total memory usage on an hourly average for Service Orchestration. This data describes the memory usage and also the requested memory and the memory limit which is set in the SO microservice helm charts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",namespace=~\"$Namespace\"}[15m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\", resource=\"cpu\", container!=\"POD\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$Namespace\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Idun Memory Usage - Hourly",
   "type": "stat",
   "description": "Metric used: container_memory_usage_bytes, kube_pod_container_resource_requests, kube_pod_container_resource_limits_memory_bytes\n\nThis graph shows the total memory usage on an hourly average for Service Orchestration. This data describes the memory usage and also the requested memory and the memory limit which is set in the SO microservice helm charts.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$Namespace\", container!=\"POD\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\", resource=\"memory\", container!=\"POD\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$Namespace\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Idun Disk Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Idun Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Idun Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"$Namespace\",kubernetes_io_hostname=~\"^$Node$\"}[15m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{namespace=~\"$Namespace\",kubernetes_io_hostname=~\"^$Node$\"}[15m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) ",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"$Namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (pod_name)",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{namespace=~\"$Namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (pod_name)",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU per container",
   "type": "bargauge",
   "description": "Metrics used: container_cpu_usage_seconds_total\n\nThis graph shows the CPU usage per Container in Service Orchestration.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\",kubernetes_io_hostname=~\"^$Node$\", container!=\"POD\"}[15m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Containers memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Containers memory usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\",image!=\"\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "Containers network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"$Namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (container_name, pod_name)",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{namespace=~\"$Namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (container_name, pod_name)",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "All processes CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "All processes CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"$Namespace\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "All processes memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\",id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "All processes network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "All processes network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"$Namespace\",id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[15m])) by (id)",
     "legendFormat": "-> {{ id }}"
    }
   ]
  }
 ]
}