{
 "title": "Idun Release K8s Deployments View",
 "description": "Deployment overview for Kubernetes deploys.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Environment", "query": "prometheus" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"},  deployment)"
    }
   },
   { "name": "deploy", "label": "Deployment", "query": { "query": "label_values(deployment)" } }
  ]
 },
 "panels": [
  {
   "title": "Deployment Replicas - Desired",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\", deployment=~\"$deploy\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\",deployment=~\"$deploy\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Up-to-date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\", deployment=~\"$deploy\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\",deployment=~\"$deploy\"})"
    }
   ]
  },
  {
   "title": "Idun Applications",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_deployment_labels{namespace=~\"$namespace\"}",
     "legendFormat": "{{deployment }}"
    },
    {
     "expr": "kube_statefulset_labels{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Generations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}