{
 "title": "EO Common Services - Container Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "label": "SOURCE", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Alerts ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 } }
   ]
  },
  {
   "title": "Common-Service API-Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Api-gateway - Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"eric-eo-api-gateway\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"eric-eo-api-gateway\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-eo-api-gateway\", job=\"eric-pm-server-kube-state-metrics\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "API-Gateway - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "core", "label": "core" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"eric-eo-api-gateway\"}[5m])",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"eric-eo-api-gateway\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"eric-eo-api-gateway\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Apigateway -- Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-api-gateway-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-api-gateway-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Transmitted  Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Common-Service Br-agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "common-br-agent - CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"common-br-agent\"}[5m])",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"common-br-agent\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"common-br-agent\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "common-br-agent - Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"common-br-agent\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"common-br-agent\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-eo-api-gateway\", job=\"eric-pm-server-kube-state-metrics\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Logtransformer - Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-common-br-agent-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-common-br-agent-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Transmitted  Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Common-Service logviewer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logviewer  - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "core", "label": "core" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"kibana\"}[5m])",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"kibana\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"kibana\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Logviewer - Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 7, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"kibana\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"kibana\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"kibana\", job=\"eric-pm-server-kube-state-metrics\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "logviewer -- Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-data-visualizer-kb-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-data-visualizer-kb-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Transmitted  Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "ADP-Logstransformer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "logtransformer - CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"logtransformer\"}[5m])",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"logtransformer\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"logtransformer\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "logtransformer - Memory ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"logshipper\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"logshipper\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-eo-api-gateway\", job=\"logshipper\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Logtransformer - Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-transformer-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-transformer-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Transmitted  Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "ADP-Logshipper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logshipper  - Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"logshipper\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"logshipper\"}))",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"logshipper\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Logshipper - CPU ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "yaxes": [
      { "format": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"logshipper\"}[5m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"logshipper\", job=\"eric-pm-server-kube-state-metrics\"}))",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"logshipper\", job=\"eric-pm-server-kube-state-metrics\"}))",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Logshipper - Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-shipper-.*\", interface=\"eth0\"}[1m]))\r",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-shipper-.*\", interface=\"eth0\"}[1m]))",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "ADP-Search engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search engine Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"searchengine\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"searchengine\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-eo-engine\", job=\"searchengineb\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Search engine- CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "cores", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"searchengine\"}[5m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"searchengine\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"searchengine\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "SearchEnigne - Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"^eric-data-search-.*\", interface=\"eth0\"}[1m]))",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "\r\nsum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-data-search-.*\", interface=\"eth0\"}[1m]))",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "ADP-Keycloak",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keycloak - Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"so\",container=\"iam\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"so\", resource=\"memory\",container=\"iam\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"so\",container=\"iam\", job=\"eric-pm-server-kube-state-metrics\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Keycloak - CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "cores", "label": "core" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"iam\"}[5m])",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"iam\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"iam\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "keycloak - Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-sec-access-mgmt-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      },
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^^eric-sec-access-mgmt-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Received Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "ADP-bro-ctrl",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-ctrl-bro - Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"eric-ctrl-bro\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"eric-ctrl-bro\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-ctrl-bro\", job=\"eric-pm-server-kube-state-metrics\"}",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-ctrl-bro - CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"so\", container=\"eric-ctrl-bro\"}[5m])",
       "legendFormat": "Usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"so\", resource=\"cpu\", container=\"eric-ctrl-bro\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"so\", container=\"eric-ctrl-bro\", job=\"eric-pm-server-kube-state-metrics\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-bro-ctrl - Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"so\", pod=~\"^eric-ctrl-bro-.*\", interface=\"eth0\"}[1m])\r\n",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"so\", pod=~\"^eric-ctrl-bro-.*\", interface=\"eth0\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    }
   ]
  }
 ]
}