{
 "title": "EVNFM HTTP metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SOURCE", "query": "prometheus" },
   { "name": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  {
   "title": "Request Rate per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$app\"}[1m]))by (uri,method)\r",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$app\", status!~\"2..\"}[1m]))by (uri,method)\r"
    }
   ]
  },
  {
   "title": "Average Response Latency per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{app=\"$app\", status!~\"500\"}[1m]))/sum(rate(http_server_requests_seconds_count{app=\"$app\", status!~\"500\"}[1m]))",
     "legendFormat": "HTTP-AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{app=\"$app\", status!~\"5..\"})",
     "legendFormat": "HTTP-MAX"
    }
   ]
  },
  {
   "title": "Response time of 50%, 75%, 90%, 95% of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"$app\"}[1m])) by (le))",
     "legendFormat": "95% "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"$app\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"$app\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"$app\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Top 10 API's by Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"$app\"}[1m])))"
    }
   ]
  }
 ]
}