{
 "title": "SO - RED Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "SOURCE", "query": "prometheus" },
   { "name": "Service", "label": "Service", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Rate per Second",
   "type": "timeseries",
   "description": "Metrics used: http_server_requests_seconds_count\n\nThis graphs shows the HTTP request rate per second of this microservices API. The data is split up by the microservice's API endpoint and the HTTP method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$Service\"}[1m]))by (uri,method)\r",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate per Second",
   "type": "timeseries",
   "description": "Metrics used: http_server_requests_seconds_count\n\nThis graphs shows the error rate per second of this microservices API. This data is collected by filtering out all HTTP responses that do not have a HTTP 2XX status. The data is split up based on the microservice's API endpoint and the HTTP method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$Service\", status!~\"2..\"}[1m]))by (uri,method)\r"
    }
   ]
  },
  {
   "title": "Average Response Latency per Second",
   "type": "graph",
   "description": "Metrics used: http_server_requests_seconds_sum, http_server_requests_seconds_max\n\nThis graph shows the total average response time and the longest response time of all successful requests that were made towards the microservice's API.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{app=\"$Service\", status!~\"500\"}[1m]))/sum(rate(http_server_requests_seconds_count{app=\"$Service\", status!~\"500\"}[1m]))",
     "legendFormat": "HTTP-AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{app=\"$Service\", status!~\"5..\"})",
     "legendFormat": "HTTP-MAX"
    }
   ]
  },
  {
   "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests",
   "type": "timeseries",
   "description": "Metric used: http_server_requests_seconds_bucket\n\nThis graph shows the response time based on the percentage of the total request made to the microservice's API. The supported percentages of requests are 50%, 75%, 90%, 95%, 99% and 100%.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[1m])) by (le))",
     "legendFormat": "95% "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"$Service\"}[1m])) by (le))",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "Top 10 API's by Request Rate",
   "type": "timeseries",
   "description": "Metric used: http_server_requests_seconds_count\n\nThis graph shows top 10 microservice's API by request rate. The data is collected by filtering based on highest number of requests that were made towards the microservice's API. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"$Service\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs by Latency",
   "type": "timeseries",
   "description": "Metric used: http_server_requests_seconds_sum\n\nThis graph shows top 10 microservice's APIs based on the longest response time. The data is collected by filtering based on highest number of longest response time that were made towards the microservice's API.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"$Service\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}