{
 "title": "SO - USE Metrics",
 "description": "Dashboard for Micrometer instrumented applications",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "SOURCE", "query": "prometheus" },
   { "name": "application", "label": "Service", "query": { "query": "label_values(app)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app=\"$application\"},  instance)"
    }
   },
   { "name": "jvm_memory_pool_heap", "label": "JVM Memory Pools Heap", "query": { "query": "" } },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Metric used: process_uptime_seconds\n\nDisplays how long this pod has been up.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{app=\"$application\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "description": "Metric used: process_start_time_seconds\n\nDisplays the time that this pod started.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{app=\"$application\", instance=\"$instance\"}*1000)"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_max_bytes\n\nDisplays a percentage of how much of the JVM heap is currently in use.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{app=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_max_bytes\n\nDisplays the percantage of the non-heap memory that is currently being used by the JVM.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{app=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Metric used: http_server_requests_seconds_count\n\nDisplays the rate of HTTP requests that are being made towards this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Metric used: http_server_requests_seconds_count\n\nDisplays the rate of HTTP error responses that this microservice is producing.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Metrics used: http_server_requests_seconds_sum, http_server_requests_seconds_count, http_server_requests_seconds_max\n\nDisplays the average and the max HTTP request response time of this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{app=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{app=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{app=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the overall count of the max, commited and used memory bytes in the heap of the JVM in this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{app=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the overall count of the max, commited and used non-heap memory bytes in the JVM of this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the overall total count of the max, commited and used memory bytes in the JVM of this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "description": "Metrics used: process_memory_vss_bytes, process_memory_rss_bytes, process_memory_swap_bytes\n\nDisplays the total VSS, RSS and swap memory bytes used in the JVM of this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_rss_bytes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap_bytes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss_bytes{app=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Metrics used: system_cpu_usage, process_cpu_usage, process_cpu_usage\n\nDisplays the CPU usage of the JVM, broken down into the system usage, the process usage and the hourly average process usage.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{app=\"$application\", instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "Metrics used: system_load_average_1m, system_cpu_count, system_cpu_usage\n\nDisplays the average system load, the total number of CPUs in use by the JVM and also the CPU usage of the JVM.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    },
    {
     "expr": "system_cpu_usage{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Metrics used: jvm_threads_live_threads, jvm_threads_daemon_threads, jvm_threads_peak_threads, process_threads\n\nDisplays the number of live, daemon and process threads in use in the JVM. This graph also displays the max process threads that were in use in the JVM.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "description": "Metrics used: jvm_threads_states_threads\n\nDisplays the count of threads in the different thread state categories currently being used in the JVM.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "description": "Metric used: logback_events_total\n\nThis graph is reading all of the log events that happen in this microservice and we can see the amount of log events categorised by the log level.",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{app=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "Metrics used: process_files_open_files, process_files_max_files\n\nDisplays the current count of open file descriptors in the JVM and also the max amount of file descriptors that the JVM can handle being open.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "description": "Metric usage:  jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the total memory bytes used by the JVM and also the total committed bytes and the max bytes that can be used by the JVM. ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the JVM metaspace memory separated by the bytes used, committed and the max amount.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the JVM metaspace memory separated by the bytes used, committed and the max amount.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "description": "Metrics used: jvm_memory_used_bytes, jvm_memory_committed_bytes, jvm_memory_max_bytes\n\nDisplays the JVM metaspace memory separated by the bytes used, committed and the max amount.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{app=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "description": "Metric used: jvm_gc_pause_seconds_count\n\nDisplay the rate the garbage collection has to complete operations.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{app=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Metrics used: jvm_gc_pause_seconds_sum, jvm_gc_pause_seconds_count, jvm_gc_pause_seconds_max\n\nDisplays the average rate of garbage collections actions and the maximum amount of time that these operations took.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{app=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{app=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "description": "Metric used: jvm_gc_memory_allocated_bytes_total, jvm_gc_memory_promoted_bytes_total\n\nDisplays the total byte that have been added to the young generation pool after garbage collection (allocated) and the number of bytes that have been added to the old generation (promoted) after garbage collection.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{app=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{app=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "description": "Metric used: jvm_classes_loaded_classes\n\nDisplays the amount of classes loaded by the JVM.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "description": "Metric used: jvm_classes_loaded_classes\n\nDisplays the change of the amount of classes loaded by the JVM.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{app=\"$application\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "description": "Metric used: jvm_buffer_memory_used_bytes, jvm_buffer_total_capacity_bytes\n\nDisplays the bytes used in the JVM buffer and the max bytes allowed to be used in the JVM buffer.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{app=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{app=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "description": "Metric used: jvm_buffer_count_buffers\n\nDisplays an estimate to the amount of buffers in the JVM.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{app=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "description": "Metric used: jvm_buffer_memory_used_bytes, jvm_buffer_total_capacity_bytes\n\nDisplays the amount of mapped bytes used and the max amount of mapped bytes in the JVM of this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{app=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{app=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "description": "Metric used: jvm_buffer_count_buffers\n\nDisplays the estimated mapped buffer count in the JVM of this microservice.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{app=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}